In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation,Flatten,Conv2D,MaxPooling2D
import pickle

In [2]:
X=pickle.load(open('X.pickle','rb'))
y=pickle.load(open('y.pickle','rb'))

In [3]:
X=X/255.0

In [4]:
import numpy as np
y=np.array(y)
y

array([0, 0, 0, ..., 0, 1, 0])

In [5]:
model=Sequential()
model.add(Conv2D(64,(3,3),input_shape=X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(64,(3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(32,(3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(32,(3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(1))
model.add(Activation('sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,y,batch_size=34,validation_split=0.2,epochs=10)

Train on 6404 samples, validate on 1601 samples
Epoch 1/10
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
6404/6404 [==============================] - 72s 11ms/sample - loss: 0.6915 - accuracy: 0.5133 - val_loss: 0.7085 - val_accuracy: 0.5209
Epoch 2/10
6404/6404 [==============================] - 61s 9ms/sample - loss: 0.6844 - accuracy: 0.5562 - val_loss: 0.6643 - val_accuracy: 0.5871
Epoch 3/10
6404/6404 [==============================] - 62s 10ms/sample - loss: 0.6502 - accuracy: 0.6266 - val_loss: 0.6409 - val_accuracy: 0.6090
Epoch 4/10
6404/6404 [==============================] - 60s 9ms/sample - loss: 0.6099 - accuracy: 0.6691 - val_loss: 0.5795 - val_accuracy: 0.7214
Epoch 5/10
6404/6404 [==============================] - 60s 9ms/sample - loss: 0.5628 - accuracy: 0.7180 - val_loss: 0.5435 - val_accuracy: 0.7452
Epoch 6/10
6404/6404 [==============================] - 63s 10ms/sample - loss: 0.5244 - accuracy: 0.7475 - val_loss: 0.5

In [8]:
import cv2

In [9]:
def prepare(filepath):
    img_size=60
    img_array=cv2.imread(filepath,cv2.IMREAD_GRAYSCALE)
    new_array=cv2.resize(img_array,(img_size,img_size))
    return np.array(new_array).reshape(-1,img_size,img_size,1)

In [10]:
a=prepare('meow.jpg')
a=a/255
a

array([[[[0.16862745],
         [0.16470588],
         [0.14509804],
         ...,
         [0.3254902 ],
         [0.39607843],
         [0.76078431]],

        [[0.15686275],
         [0.15686275],
         [0.1372549 ],
         ...,
         [0.4       ],
         [0.35686275],
         [0.75294118]],

        [[0.15294118],
         [0.15686275],
         [0.21960784],
         ...,
         [0.36470588],
         [0.38431373],
         [0.79215686]],

        ...,

        [[0.09411765],
         [0.08627451],
         [0.09019608],
         ...,
         [0.22745098],
         [0.36862745],
         [0.19215686]],

        [[0.08235294],
         [0.07843137],
         [0.09019608],
         ...,
         [0.14901961],
         [0.32941176],
         [0.23137255]],

        [[0.09803922],
         [0.09411765],
         [0.09019608],
         ...,
         [0.31764706],
         [0.33333333],
         [0.10588235]]]])

In [11]:
pred=model.predict([a])

In [12]:
pred

array([[0.99386]], dtype=float32)